### ISSUE TITLE
Add 'scope' parameter/ARM property

### ISSUE THREAD

**Issue by jesseloudon** [globalbao/terraform-azurerm-policy-exemptions#2]
need to add the missing 'scope' parameter/ARM property and allow for value to be null if or use the TF 'resourceGroupName' value if scope is not specified

**Comment by mlcooper** [comment]
@jesseloudon I have implemented the built-in Azure policy called **"Audit delegation of scopes to a managing tenant"** (category is `LightHouse`). It is possible that multiple LightHouse `registrationAssignment`'s can be created in more than one subscription within an Azure tenant. 

I _believe_ in order to create more than one exemption for these multiple LightHouse configurations within a tenant, I would need to use this `scope` parameter with a `for_each` in front of it to create these multiple exemptions. It says [here](https://docs.microsoft.com/en-us/azure/templates/microsoft.authorization/policyexemptions?tabs=json#template-format) that the value of `scope` is a `string` (not a list of strings). 

Would you agree that I'm approaching this in the correct way and I would need to make use of this `scope` parameter?

**Comment by jesseloudon** [comment]
hey @mlcooper - great Q

I do think multiple exemption resources are the way to go in your particular use case w/ either a **count** or **for_each** on this exemption module. I have a **count** example here if that helps! https://github.com/globalbao/terraform-azurerm-policy-exemptions/tree/main/examples/count

Regarding usage of the **scope** parameter:

- this is designed for setting the scope of the exemption resource to be different to the ARM template's deployment scope - important to know this in the context of using this exemption module which creates the deployment to a specific **resource group** scope
- yes looks like **scope** is a **string** so only 1 value can be passed in
- I need to add/test the **scope** parameter usage in this module per this open issue 😄

**Comment by mlcooper** [comment]
@jesseloudon do you know what the value of the `scope` parameter would be if I wanted to create an exemption for a Resource Group that has ID `/subscriptions/1111111-2222-3333-4444-555555555555/resourceGroups/rg-resources-policy-dev`?

I'm asking because I have not been able to find any examples of what the value for the `scope` parameter would be, either in Azure's documentation or in someone's public code on github.

**Comment by jesseloudon** [comment]
hi @mlcooper 

I'm thinking that the RG ID or resource ID you pass into the **Scope** parameter would need to be in the **same subscription context as the Terraform deployment for the policy exemption**.

Additionally, if you need to target multiple subscriptions for policy exemptions from your calling/parent Terraform module you can use provider aliases as per this example: https://github.com/globalbao/terraform-azurerm-policy-exemptions#create-2-policy-exemptions-targeting-rgs-in-two-different-subscriptions
